services:
  frontend_react:
    container_name: frontend_react
    build: 
      context: ./FrontEnd
    volumes: 
      - ./FrontEnd:/usr/src/app
    ports:
      - 5173:5173
    networks:
      - reseauApplication

  microservice_authentification:
      container_name: microservice_authentification
      build: 
        context: ./BackEnd/microservice/authentification
      volumes: 
        - ./BackEnd/microservice/authentification:/usr/src/app
      ports:
        - 3000:3000
      networks:
      - reseauApplication

networks:
  reseauApplication:
    driver: bridge
    external: true